### ISSUE TITLE
Change wallpaper every x minutes

### ISSUE THREAD

**Issue by viss02** [ifl0w/RandomWallpaperGnome3#1]
Hello,

will you make function that will change wallpaper every x minutes in future?
This option will be so great :heart: 

Thanks

**Comment by ifl0w** [comment]
Hello, 

This feature ist basically already implemented on the rework branch but needs some fine tuning. 
I hope I find some time during the next months to finish that branch and add some other really handy features. 

If you really want to use the feature now you kann download the branch and install the extension manually. I am currently using this branch and it works pretty well but the images are fetched from https://alpha.wallhaven.cc/ on this branch and there are currently no options to switch the source. 

Thank you for your feedback!

**Comment by ifl0w** [comment]
Hello, I just merged the rework branch into master. So this feature is implemented and can be activated in the extension settings. :+1:
