### ISSUE TITLE
unsplash not working!

### ISSUE THREAD

**Issue by smalltimer** [ifl0w/RandomWallpaperGnome3#103]
Hi, 

First, thank you for this fantastic extension and for sharing it with the community. 

I'm on gnome-shell 3.30.2 (Debian Buster) and unsplash and Desktoppr do not seem to work. Is this a known issue? If not, I'd be happy to provide whatever details are needed to register it as an issue. 

Thanks very much!

**Comment by AlexWayfer** [comment]
I'm fetching images via Unsplash seems working. I have such settings:

![image](https://user-images.githubusercontent.com/6510020/119384303-28936d00-bccd-11eb-98fb-db77023ea0cf.png)


Can you please describe what do you see, why do you think it doesn't work? 

Also I don't see a source named "Desktoppr", is it your custom?

**Comment by smalltimer** [comment]
Hi, 

I do see Desktoppr as an option! Here's a screenshot:
![desktoppr-option](https://user-images.githubusercontent.com/14436654/119394402-6a72e200-bcd2-11eb-88de-260f238020d6.png)

I'm also attaching a screenshot for the unsplash settings I use:
![unsplash-settings](https://user-images.githubusercontent.com/14436654/119394454-78c0fe00-bcd2-11eb-987e-01c1f447c108.png)

These settings worked until very recently. I can't say what exactly broke the extension, but if you have some ideas, I can go through the logs. Both unsplash and desktoppr have stopped working - the wallpaper does not change daily, and hitting the 'Request New Wallpaper' button does not do anything. If I had to guess, I would say that there's an issue with how the extension integrates with gnome 3.30.2. 

Cheers

**Comment by AlexWayfer** [comment]
@smalltimer quick search by "Desktoppr" in this repo gives us #100, in which this source was removed. Also I noticed a different tabs order from mine, so I guess you have an old version of the extension. Also, GNOME 3.30 is very old (released in September 2018), and there is GNOME 40 already, so… I suggest you to move forward and update extension w/ or w/o GNOME (I don't know, maybe there is a GNOME versions lock for newer versions of the extension itself).

**Comment by smalltimer** [comment]
@AlexWayfer I'm on Debian stable - so I'm not looking to upgrade my gnome-shell (the joys of ultra-stability...). Thanks a lot for looking into it though! I am guessing unsplash changed their API and the older version of the extension which works with my gnome-shell does not use this. Too bad :(

Debian Bullseye will be release shortly though, and I'm planning to upgrade . Hopefully it will have a gnome-shell version that is compatible with this extension. Unless, of course, the dev decides to make the API changes for gnome-shell 3.30! So leaving it open till the dev pops by and says they won't. Also, apologies if you're the dev @AlexWayfer  :D

**Comment by AlexWayfer** [comment]
> Also, apologies if you're the dev @AlexWayfer :D

FYI: If I'd be a dev for this repo, I'd have a badge "Member" or "Collaborator" or "Owner" in the same place, where you have the "Author" badge for this issue:

![image](https://user-images.githubusercontent.com/6510020/119406687-ce55d480-bceb-11eb-900d-96a27661d1d3.png)

So, no, and OK, let's wait for @ifl0w's opinion and decision.

**Comment by smalltimer** [comment]
AHA. Thanks for the info.

**Comment by ifl0w** [comment]
Hello @smalltimer! Unfortunately, you are using an older version that is not actively supported by me anymore as @AlexWayfer noted correctly. Supporting and especially testing multiple gnome-shell versions is quite an effort and I decided to not do it anymore, but I'd be happy to accept PRs that fix the extension for older versions and are tested by other users. These legacy versions would be maintained in different branches and not be updated by myself though. So please feel free to backport or fix the version for your current shell! :)

Maybe, it would be better to simply deactivate the extension for older gnome-shell versions regardless of whether they still work or not so that there is less confusion about "official" support. Maybe you have an opinion on that?

**Comment by smalltimer** [comment]
@ifl0w Thank you for the elaborate response! I'm afraid my programming skills are far too weak to be able to fix this :( But it makes a lot of sense for you to drop support for old gnome-shell versions. Imho perhaps it might be better to deactivate the extension for older gnome-shells (I am guessing you mean on the extensions website). You could always have a link to the github releases in the description and mention that adventurous users can have a go at tweaking/fixing the extension for older gnome-shells. Of course, only my two cents.

In any case, thank you for maintaining and sharing this fantastic extension with the community, and I am looking forward to using it again once I move to Debian Bullseye !

**Comment by ifl0w** [comment]
@smalltimer thanks for the feedback! I think I'll deactivate the old versions in the future. Probably most of them do not work correctly anymore anyways. :)
