### ISSUE TITLE
GNOME 41 Support

### ISSUE THREAD

**Issue by bobdanks** [ifl0w/RandomWallpaperGnome3#118]
With GNOME 41's release, i found that the Random Wallpaper extension was automatically disabled due to lack of support for the new version.

However, after modifying my metadata.json file to include "41" support, it seems to be fully functional.

Can you please investigate and update as needed?

**Comment by pascallj** [comment]
PR https://github.com/ifl0w/RandomWallpaperGnome3/pull/114 already addresses this issue. Unfortunately it seems @ifl0w hasn't been available for some time.

**Comment by bobdanks** [comment]
Ahh. Thanks, I didn't see that PR... I'll close the issue.
