### ISSUE TITLE
Add a keyboard shortcut for changing the wallpaper 

### ISSUE THREAD

**Issue by tanaybhomia** [ifl0w/RandomWallpaperGnome3#126]
Title says it all
Lets us add a keyboard shorcut so that we can change the wallpaper without using mouse

**Comment by ifl0w** [comment]
This can be done in v3.0.0 by mapping the terminal command mentioned in
https://github.com/ifl0w/RandomWallpaperGnome3/issues/166#issuecomment-1937915394 to your keyboard shortcut. I just tested this with the keyboard settings in the gnome settings app and it seems to work great :)!
