### ISSUE TITLE
I love it but it's not compatible with gnome 42

### ISSUE THREAD

**Issue by crashbit666** [ifl0w/RandomWallpaperGnome3#129]
I love this app, but it's not compatible with gnome 42. 
Are there plans to make it compatible?
Thank you

**Comment by ifl0w** [comment]
Thank you for your Contribution! 

I tried the app on Gnome OS (version 42) and the extension fundamentally works. 
There are some minor UI bugs (some text is not aligned and the settings window has some unnecessary padding).
I also recognized that there is a bug in the "Auto-Fetching" feature where two images are requested instead of one and the history becomes broken (this seems to be unrelated to Gnome 42).
Unfortunately, I am very busy right now but I'll try to fix the most important problems and release a new version for Gnome 42 a.s.a.p.

For now, you can deactivate the extension version validation with the dconf editor under "/org/gnome/shell/disable-extension-version-validation". This allows you to use versions of extensions that do not officially support your current Gnome version (at your own risk, of course). 

Feel free to report any further bugs you recognize! :)

**Comment by crashbit666** [comment]
Thank you. First day I try the extension on ubuntu 22.04 (testing) and worked well. After ubuntu made some change and the extension downloads images but can't change wallpaper. I don't know how to debug the extension. I try some options and I can see that when I pick on request new wallpaper:

`Object St.BoxLayout (0x55cf8c4c9c50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55cf85f94170 ==
#0   55cf8afe5248 i   resource:///org/gnome/shell/ui/popupMenu.js:787 (11062611740 @ 22)
#1   55cf8afe51a8 i   resource:///org/gnome/shell/ui/popupMenu.js:805 (110626118d0 @ 23)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:144 (23f214506fb0 @ 32)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:157 (23f21450c060 @ 77)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
Object St.BoxLayout (0x55cf8c4c9c50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77befd40 b   resource:///org/gnome/shell/ui/environment.js:62 (330761bcc150 @ 20)
#1   7ffc77befe50 b   resource:///org/gnome/shell/ui/popupMenu.js:711 (11062611470 @ 65)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:151 (23f214506fb0 @ 150)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:157 (23f21450c060 @ 77)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77bef6e0 b   resource:///org/gnome/shell/ui/environment.js:62 (330761bcc150 @ 20)
#1   7ffc77befe50 b   resource:///org/gnome/shell/ui/popupMenu.js:747 (11062611470 @ 518)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:151 (23f214506fb0 @ 150)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:157 (23f21450c060 @ 77)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
Object St.BoxLayout (0x55cf8c4c9c50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.BoxLayout (0x55cf88e167e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77bef760 b   resource:///org/gnome/shell/ui/popupMenu.js:787 (11062611740 @ 22)
#1   7ffc77befe80 b   resource:///org/gnome/shell/ui/popupMenu.js:713 (11062611470 @ 97)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:294 (23f21450c790 @ 344)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:179 (23f21450c060 @ 238)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77befe80 b   resource:///org/gnome/shell/ui/popupMenu.js:716 (11062611470 @ 177)
#1   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:294 (23f21450c790 @ 344)
#2   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:179 (23f21450c060 @ 238)
#3   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
== Stack trace for context 0x55cf85f94170 ==
Object St.BoxLayout (0x55cf88e167e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
#0   7ffc77befe80 b   resource:///org/gnome/shell/ui/popupMenu.js:749 (11062611470 @ 568)
#1   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:294 (23f21450c790 @ 344)
#2   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:179 (23f21450c060 @ 238)
#3   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
Object St.BoxLayout (0x55cf88e167e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.BoxLayout (0x55cf88e53c50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77befe90 b   resource:///org/gnome/shell/ui/popupMenu.js:787 (11062611740 @ 22)
#1   7ffc77beff60 b   resource:///org/gnome/shell/ui/popupMenu.js:805 (110626118d0 @ 23)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:144 (23f214506fb0 @ 32)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:157 (23f21450c060 @ 77)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
Object St.BoxLayout (0x55cf88e53c50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77befe10 b   resource:///org/gnome/shell/ui/environment.js:62 (330761bcc150 @ 20)
#1   7ffc77beff20 b   resource:///org/gnome/shell/ui/popupMenu.js:711 (11062611470 @ 65)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:151 (23f214506fb0 @ 150)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:157 (23f21450c060 @ 77)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77befe10 b   resource:///org/gnome/shell/ui/environment.js:62 (330761bcc150 @ 20)
#1   7ffc77beff20 b   resource:///org/gnome/shell/ui/popupMenu.js:747 (11062611470 @ 518)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:151 (23f214506fb0 @ 150)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:157 (23f21450c060 @ 77)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
Object St.BoxLayout (0x55cf88e53c50), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.BoxLayout (0x55cf8945fe60), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77befe90 b   resource:///org/gnome/shell/ui/popupMenu.js:787 (11062611740 @ 22)
#1   7ffc77beff50 b   resource:///org/gnome/shell/ui/popupMenu.js:713 (11062611470 @ 97)
#2   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:294 (23f21450c790 @ 344)
#3   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:179 (23f21450c060 @ 238)
#4   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77beff50 b   resource:///org/gnome/shell/ui/popupMenu.js:716 (11062611470 @ 177)
#1   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:294 (23f21450c790 @ 344)
#2   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:179 (23f21450c060 @ 238)
#3   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
== Stack trace for context 0x55cf85f94170 ==
#0   7ffc77beff50 b   resource:///org/gnome/shell/ui/popupMenu.js:749 (11062611470 @ 568)
#1   55cf8afe50f8 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:294 (23f21450c790 @ 344)
#2   55cf8afe5018 i   /home/crashbit/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/randomWallpaperMenu.js:179 (23f21450c060 @ 238)
#3   7ffc77bf0ba0 b   self-hosted:1181 (330761bb0a10 @ 454)
Object St.BoxLayout (0x55cf8945fe60), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.BoxLayout (0x55cf8945fe60), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
`

**Comment by ifl0w** [comment]
I did not encounter the error you mentioned. 

Is this still happening to you or is the extension working correctly now?

**Comment by crashbit666** [comment]
The problem persist. I can't get wallpapers. When I click to request new wallpaper nothing happens. I can see the wallpapers are downloaded in history folder. I'm using Ubuntu 22.04 dev version and I'm using wayland. I will try with xorg to see if it works

**Comment by crashbit666** [comment]
Same problem with xorg. I don't know what ubuntu do with wallpapers. I think it's a problem with ubuntu 22.04 testing

**Comment by dpriedel** [comment]
Hi
I just upgraded to Gnome 42 on Manjaro unstable.  

I am having the same problem with wallpapers not showing on the desktop.  My system journal has messages like the messages posted above also.

**Comment by crashbit666** [comment]
The problem persist with Ubuntu 22.04 stable. The script download images, but there are not applied.

Please, if I can do anything to debug, say me and I try to help

**Comment by Santho07** [comment]
Same problem in Pop!_OS 22.04 LTS

**Comment by PauloFerreira25** [comment]
42, OUTDATE
![image](https://user-images.githubusercontent.com/1591772/166001877-86af4ceb-10f6-4c78-9d87-ee097c0952ba.png)
:(

**Comment by yuriifabirovskyi** [comment]
In my case the extension only works with a light theme. The dark theme has a default wallpaper.
![image](https://user-images.githubusercontent.com/20482699/168169366-2ead8146-3a55-4a84-9b34-d877296ebecd.png)
In this image it is clearly visible. When i request a new image the background changes only in a light theme.

**Comment by crashbit666** [comment]
> In my case the extension only works with a light theme. The dark theme has a default wallpaper. ![image](https://user-images.githubusercontent.com/20482699/168169366-2ead8146-3a55-4a84-9b34-d877296ebecd.png) In this image it is clearly visible. When i request a new image the background changes only in a light theme.

Yes, it's true. It only happen with dark theme activated.

**Comment by crashbit666** [comment]
I have a solution. While my pull request was not accepted. You can edit this file:
- ~/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/wallpaperController.js

search "dark" and modify this line
- property = "picture-uri-dark";
to:
- let property = "picture-uri-dark";

**Comment by HipyCas** [comment]
Should I be able to install this on Gnome 42.2? The gnome extensions store says it is incompatible with my version though as far as I'm reading it looks like you got it working on Gnome 42.

**Comment by ifl0w** [comment]
I finally released the version supporting Gnome 42 & 43 yesterday on extensions.gnome.org. Sorry for taking so long. 

I didn't change a log, and I never noticed the error posted here (can't reproduce it). Can someone confirm whether this issue still exists or can it be closed?

**Comment by WellBloud** [comment]
It works fine now, thank you

**Comment by PauloFerreira25** [comment]
I installed it today, it's working fine so far.
thank you so much

**Comment by ifl0w** [comment]
Great! Thanks for testing and confirming! :)
