### ISSUE TITLE
not work on gnome-shell 3.20.4

### ISSUE THREAD

**Issue by craigwu9** [ifl0w/RandomWallpaperGnome3#13]
When I want to open config dialog from gnome-tweak-tool, it pop a dialog and show message as below:
-----------------------------------------------------------------------------
SyntaxError: illegal character

Stack trace:
  @/home/***/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/prefs.js:19
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:238
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:376
  @<main>:1
--------------------------------------------------------------------------------
And the gnome-tweak-tool shows failed to load the extension.
Gnome-shell version is 3.20.4

**Comment by ifl0w** [comment]
Did you install the version from https://extensions.gnome.org/extension/1040/random-wallpaper/
or did you install it directly from this repository?

The version from extensions.gnome.org was broken and I submitted a new one which has to be reviewed.
The code in this repository on the master branch should work on gnome 3.20.

**Comment by craigwu9** [comment]
I installed directly from this git repository.

**Comment by ifl0w** [comment]
I am sorry but I am not able to reproduce this bug. Just tested the extension again and it worked flawless on openSUSE 42.3.

Which distribution do you use? And did you install the the extension with the install script or manually?

![screenshot from 2017-07-27 13-18-08](https://user-images.githubusercontent.com/5549805/28667978-280c2310-72ce-11e7-9ef0-79103efcf126.png)

**Comment by craigwu9** [comment]
It's weird, I just cloned today. It seems I did not got lasted version. I pulled again, It works.

**Comment by ifl0w** [comment]
Well ok :) At least I don't have to release a hotfix :D
