### ISSUE TITLE
New Gnome's day/night theme not fully supported

### ISSUE THREAD

**Issue by SscSPs** [ifl0w/RandomWallpaperGnome3#138]
https://youtu.be/G1GPIheAer4
The wallpaper is not changed in dark theme selected from gnome settings
The wallpaper is still changed in the other theme. The video demonstrate the issue I'm talking about.
Not sure if its an issue in the project or somewhere else

**Comment by neblogas** [comment]
It's a known issue. The version from here is working but gets downgraded automaticaly.

**Comment by SscSPs** [comment]
can we bump the version so that it won't get downgraded automatically?

**Comment by ifl0w** [comment]
Should be resolved.
