### ISSUE TITLE
[Feature request] Ability to "ban" or blacklist a wallpaper

### ISSUE THREAD

**Issue by dangzo** [ifl0w/RandomWallpaperGnome3#139]
Might be useful to have a way to blacklist wallpapers, in case one is not relevant or liked.

The way I see it is having an entry action in `Current Background` (*for current wallpaper*) or on any of the retrieved wallpaper items, somewhere between `Image From: ...` entry and before or after the image preview:

![image](https://user-images.githubusercontent.com/8135382/186682994-1b46906c-aca2-4a9f-9528-4db7e3c1be6f.png)

Ideally, I can imagine this feature supporting the following:
- ability to blacklist a single wallpaper
- ability to whitelist it again
- ability to see current list of blacklisted wallpapers
- both blacklist/whitelist dependent on wallpaper source (Wallhaven, Reddit, etc)

Let's comment down below for any idea.

**Comment by ifl0w** [comment]
Implemented in v3.0.0.
