### ISSUE TITLE
[Feature request] Option to add wallpapers to favourites

### ISSUE THREAD

**Issue by adomo88** [ifl0w/RandomWallpaperGnome3#16]
It would be nice if you could choose an image as favourite so that one wouldn't be erased from the history, or would be copied to other folder or something.

**Comment by ifl0w** [comment]
Thank you for the request. I already thought about that feature but this has not the highest priority for me because I want to enhance the stability and code quality as well.

Currently you have to save the wallpaper you want to keep to another location.
