### ISSUE TITLE
An option for local files

### ISSUE THREAD

**Issue by HipyCas** [ifl0w/RandomWallpaperGnome3#161]
I wanted so much the option to serve from a local folder, as many others before me like in issues #160, #87, #68 or #30. As I wait for a official implementation, I created a small server application with Rust that can serve the local folder in a compatible manner with this extension. I have published it on [Codeberg](https://codeberg.org/HipyCas/random-wall) as well as on [GitHub](https://github.com/HipyCas/random-wall) (as a kind of manual mirror) so everyone can used at least while the native option is not implemented.

I've seen that in the Wiki you have a couple [examples] on how to set up the _Generic JSON_ option, so it would be nice if it could be put in there in some way :D. The configuration would depend on how the user installs it (maybe on a server, which port, etc.), but it is of this form:

- Request URL: `<baseurl>/`
- JSON Path: `$`
- Image URL prefix: `<baserurl>`

The idea was to make the configuration the simplest possible. All the details about installation and configuration con be found in the repo README. And also thanks for this incredible extension :D.

**Comment by ifl0w** [comment]
This is already in the works!

**Comment by ifl0w** [comment]
Thanks for your contribution! This is a nifty workaround for the missing local folder support! |
@Lucki has already started work on a local folder implementation. However, your implementation might be an interesting thing to look at.

**Comment by ifl0w** [comment]
Supported in v3.0.0.
