### ISSUE TITLE
Not compatible with gnome 44

### ISSUE THREAD

**Issue by Xathros1** [ifl0w/RandomWallpaperGnome3#165]
Current metadata forces to stay at gnome 43, it would be nice if it could support 44 too

Thanks a lot

**Comment by ifl0w** [comment]
Thanks! I'm still on 43 and will update the `meta.json` once I switch to 44.

Feel free to change the `meta.json` locally and report back whether you find any obvious errors.

**Comment by Strykar** [comment]
Any update on this? Happy to help test!

**Comment by ziadkhouri** [comment]
Tested and works on Ubuntu. @Strykar want to try? https://github.com/ifl0w/RandomWallpaperGnome3/pull/169

**Comment by ifl0w** [comment]
Just updated the repository for Gnome 44. 
The new release only includes minor changes.
