### ISSUE TITLE
Requesting new wallpaper from terminal,

### ISSUE THREAD

**Issue by osmangund** [ifl0w/RandomWallpaperGnome3#166]
Hi, thank you for your great work. I use auto-fetching but sometimes I get low-quality wallpapers, and I want to request new wallpaper easily, from terminal. Can I do that?

**Comment by ifl0w** [comment]
Hey, with the current release, this is not possible. However, it should be possible by setting a flag using `gsettings` once the amazing work of @Lucki is merged and we release a new **major** version.

Note that there is no release date for this work, and it will probably still take a bit to make this a proper release.

**Comment by ifl0w** [comment]
This can be done in v3.0.0 with the following command
```
dconf write /org/gnome/shell/extensions/space-iflow-randomwallpaper/backend-connection/request-new-wallpaper true
```
