### ISSUE TITLE
Feature Request: Unsplash Curated 

### ISSUE THREAD

**Issue by PHLAK** [ifl0w/RandomWallpaperGnome3#17]
When using Unsplash as the source I would like to restrict it to their [curated photos](https://unsplash.com/documentation#list-curated-photos). I feel these photos (generally) make better wallpapers than many of the random photos I get currently.

**EDIT:** Actually, just passing the `featured` parameter in the [random photo](https://unsplash.com/documentation#get-a-random-photo) query string might be all that's needed.  This emulates the [Unsplash Instant](https://instant.unsplash.com/) Chrome extension.

**Comment by ifl0w** [comment]
I implemented the option in a new branch. This will merged into develop when I am not encountering any problems. Feel free to try it. ;)

**Comment by PHLAK** [comment]
Awesome, thanks!
