### ISSUE TITLE
Can't retrieve photos from unsplash

### ISSUE THREAD

**Issue by lillee205** [ifl0w/RandomWallpaperGnome3#171]
Every time I try to generate a wallpaper with unsplash as a source, an image that says "we couldn't find that image" shows up. The other sources work fine, however.

**Comment by crashbit666** [comment]
Same problem here. Only happens with unsplash. Constrained, ID, etc ...

**Comment by Tarch1** [comment]
works for me too with the collection ID

**Comment by ifl0w** [comment]
I noticed that the unsplash random API is a bit unstable as of late but it is supposed to still work. Maybe I'll not use it as the default source anymore for that reason.

@lillee205 can you confirm whether it is working for you again?

**Comment by lillee205** [comment]
Yup, it's fine now
