### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by mtompkins** [ifl0w/RandomWallpaperGnome3#197]
Just fell in love with this extension ... 
Hope we get a version for Gnome 46
:crossed_fingers:

**Comment by ifl0w** [comment]
Just created the release and uploaded a build to [extensions.gnome.org](https://extensions.gnome.org/extension/1040/random-wallpaper/). Once reviewed and accepted it will be available there.

Shoutout to @Lucki for the contributions and help!
