### ISSUE TITLE
Unsplash Collection

### ISSUE THREAD

**Issue by KennyStier61** [ifl0w/RandomWallpaperGnome3#23]
Instead of choosing a user or tag to display photos from, it would be neat to be able to pull a random image from a collection. You could have a text box in the settings for a place to enter a collection number. 
https://unsplash.com/collections/221037/

**Comment by ifl0w** [comment]
Hello and thank you for your suggestion.
This is already on my todo list.

**Comment by ifl0w** [comment]
Finally, this is implemented and will be included in the next release.
You can test it out on the develop branch. :)
