### ISSUE TITLE
gnome-shell 3.22.3 logs "too much recursion", but still works

### ISSUE THREAD

**Issue by gnarendran** [ifl0w/RandomWallpaperGnome3#31]
Extension obtained from extensions.gnome.org. Logs are thrown whether "Disable hover preview" is on or off.
========================
Oct 24 11:16:08 user gnome-shell[1804]: JS LOG: RWG3 [INFO] >> WallpaperController :: Requesting image: http://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-304917.jpg
Oct 24 11:16:11 user gnome-shell[1804]: JS ERROR: Error calling onComplete: InternalError: too much recursion
                                              _wrapTweening@resource:///org/gnome/shell/ui/tweener.js:56
                                              addTween@resource:///org/gnome/shell/ui/tweener.js:39
                                              @/home/user
/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:252
                                              _addHandler/params[name]@resource:///org/gnome/shell/ui/tweener.js:91
                                              _addHandler/params[name]@resource:///org/gnome/shell/ui/tweener.js:91
...<snip>...
                            _callOnFunction@resource:///org/gnome/gjs/modules/tweener/tweener.js:203
                                              _updateTweenByIndex@resource:///org/gnome/gjs/modules/tweener/tweener.js:333
                                              _updateTweens@resource:///org/gnome/gjs/modules/tweener/tweener.js:345
                                              _onEnterFrame@resource:///org/gnome/gjs/modules/tweener/tweener.js:360
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:124
                                              ClutterFrameTicker<._onNewFrame@resource:///org/gnome/shell/ui/tweener.js:208
                                              wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                              ClutterFrameTicker<._init/<@resource:///org/gnome/shell/ui/tweener.js:183
===========================

**Comment by ifl0w** [comment]
Hello and thank you for your report!

Unfortunately, I am not encountering this bug on Gnome 3.26 and I guess it is a gnome-shell bug.
The bug is part of the loading animation of the extension icon and therefore disabling the hover preview wont change anything about it.

Is this bug resulting in any misbehavior of the extension or your system? If it is not critical I'll take look at it when I have the time to setup an Gnome 3.22.3 system and reproduce the bug.

I suggest updating to a newer version of Gnome for now, if possible.

**Comment by gnarendran** [comment]
Thanks for the response!  I am on CentOS7.4 for which gnome 3.22.3 is the latest version. There is no misbehavior of the extension at all, just the logs, so not critical. I tried "disabling hover preview" just in case, as it is mentioned as a workaround for a gnome crash - I don't face that issue. Regards,Narendran Gopalakrishnan. 

    On Tuesday, October 24, 2017 11:52 PM, Wolfgang Rumpler <notifications@github.com> wrote:
 

 Hello and thank you for your report!Unfortunately, I am not encountering this bug on Gnome 3.26 and I guess it is a gnome-shell bug.
The bug is part of the loading animation of the extension icon and therefore disabling the hover preview wont change anything about it.Is this bug resulting in any misbehavior of the extension or your system? If it is not critical I'll take look at it when I have the time to setup an Gnome 3.22.3 system and reproduce the bug.I suggest updating to a newer version of Gnome for now, if possible.—

**Comment by ifl0w** [comment]
I'll no longer support gnome-shell versions < 3.28.
Therefore, I will not look into old bugs anymore and I will close old issues that don't seem to exist on the newer shell versions.

I am sorry for the inconvenience.
