### ISSUE TITLE
Spelling Error and a small request

### ISSUE THREAD

**Issue by aksumka** [ifl0w/RandomWallpaperGnome3#33]
Heya, wallhaven's owner here!

Looks like there's a small misspelling of wallhaven in the app's settings UI. We do own the wallheaven.cc domain, but our actual name is wallhaven.

Second, could the link to the image be changed to link to the showcase view? I think users would get more use of of viewing the wallpaper's showcase page over just the image.

Thanks!

**Comment by ifl0w** [comment]
Hey!

Thank you for the information!

I'll take a look at it and will try to fix it with the next update.
