### ISSUE TITLE
Don't reset timer at start up

### ISSUE THREAD

**Issue by AlexWayfer** [ifl0w/RandomWallpaperGnome3#38]
Hello!

I want to change wallpapers daily.

I set interval 12 hours and expected that every real 12 hours (or next day) I'll get a new wallpaper.

But I don't work 12 hours, and after each start up I see countdown from 12 hours.

Please, save the last change date, and at start check `if now >= changed_date + interval`.

**Comment by ifl0w** [comment]
I know this issue and it bothered me as well when I was implementing the feature.
Back then I did not find a way to receive a "shutdown" event during which it was possible to store the remaining time in a clean way. The other option would have been to store the remaining time every minute but that solution is too dirty in my opinion.

I'll look into it in the future. Maybe there is such a feature today and the documentation is more clear about it or maybe I can find another extension that has found a good workaround for this problem.

Any suggestions are welcome!

**Comment by ifl0w** [comment]
I did not find an excuse for not storeing the last changed timestamp and performing the suggested check on startup. 
I'll try to implement the fix as soon as possible.

**Comment by AlexWayfer** [comment]
Thank you! I'll wait.

**Comment by ifl0w** [comment]
I fixed it. 
It currently is only in the develop branch and will be included in the next release, but I don't know when this will be. 

You might give it a try by installing the extension directly from the repository. 

Currently, the extension does not calculate the correct remaining time after a restart if the interval was surpassed. This means that if you set 12h as interval and restart the machine after 13h it will change the background and set the remaining time to 12h instead of the "more correct" 11h. 

I think that the "correct" calculation would be better and probably will implement it this way. Any feedback is welcome! :)

**Comment by AlexWayfer** [comment]
> Currently, the extension does not calculate the correct remaining time after a restart if the interval was surpassed. This means that if you set 12h as interval and boot the machine after 13h it will change the background and set the remaining time to 12h instead of the "more correct" 11h.
> 
> I think that the "correct" calculation would be better and probably will implement it this way. Any feedback is welcome! :)

I think… there is can be `Daily` option. But I also think that counting only working time can be the best and more intuitive approach.

So, if you set 5 hours interval, and work 4 hours — you'll see a new background after 1 hour of the next boot. If you work 6 hours — you'll see a new background 1 hour before shutting down and another one after 4 hours of the next boot.

What do you think?

**Comment by ifl0w** [comment]
For only counting the working hours, it would be required to know when the system was shut down. As I mentioned in my first reply, this wasn't really achievable when I implemented the feature. 
It might be now but I have no time to check that. 

The easy options are:
* Using the real time. This means that the interval won't be paused if the system is shut down. This is what you suggested in the first place if I am not wrong.
* Reverting to the former implementation where the interval is reset during the boot.

I personally would like working hour version or the real-time version. I guess the real-time version is probably what the most people would think of.

**Comment by AlexWayfer** [comment]
> For only counting the working hours, it would be required to know when the system was shut down.

Oh, yes, sorry.

> I personally would like working hour version or the real-time version. 

OK, I'd like this version too.

**Comment by ifl0w** [comment]
So, I implemented the real-time version for now. Only time will tell if people are satisfied with this. :)
You can try it on the develop branch.

Thank you for your help! :+1:

**Comment by AlexWayfer** [comment]
Thank you for your work!

I'll wait a release, I think.

**Comment by AlexWayfer** [comment]
I don't know, can I write here, or a new issue is better.

I faced with non-intuitive behavior:

1. You have 5 hours interval
2. You turned off  computer after 4 hours
3. You turned on computer after 5 hours and 50 minutes
4. Your wallpaper instantly changed, and a new will be after 10 minutes.

I think interval should be reset after wallpaper changing.

**Comment by ifl0w** [comment]
Hello, I'll reopen this issue if nessecary. 

This behavior is somewhat expected. 
Imagine an interval of 12h and you activate the timer at 12pm. So you would expect the wallpaper to change ever 12h of real time. (at 12am and at 12pm) 
If we would reset the timer, it would shift the start time and I guess this would also lead to some unintuitive behavior since the wallpaper would not change at a consistent rate anymore (not at 12am and 12pm).

I think that the implicit start time of the timer is a problem but I am not sure what the best solution would be.

I think that the implicit starting time point

**Comment by AlexWayfer** [comment]
I think, we're expecting different things, with different intervals (probably).

You're talking about "want to see change at the specific time of day".

I'm talking about "want to see one wallpaper N hours".

And, probably, scheduled switch isn't "interval".

**Comment by ifl0w** [comment]
I understand where you are coming from but its just a question of what phrasing and behavior is suited and expected.

I don't know what most people expect.

The change in the code should be trivial.

**Comment by AlexWayfer** [comment]
Maybe there is should be choice (via radio buttons) between schedule (time pick, from 00:00 to 23:59) and interval (like now, number of hours).

**Comment by ifl0w** [comment]
This sounds reasonable. We should track it as feature request since this could take a couple hours.
I'll implement it when I have more time.

I could also implement your requested behaviour in a separate branch if you like.

**Comment by AlexWayfer** [comment]
> This sounds reasonable. We should track it as feature request since this could take a couple hours.
I'll implement it when I have more time.

Cool, thanks!

> I could also implement your requested behaviour in a separate branch if you like.

As a temporary resolution? No, thank you. I can live with the current behavior. :slightly_smiling_face:
