### ISSUE TITLE
Hangs on Manjaro gnome (Xorg) 3.30.1

### ISSUE THREAD

**Issue by tnilzon** [ifl0w/RandomWallpaperGnome3#46]
At wallpaper change the extension hangs and causes high cpu on Manjaro gnome 3.30.1. Only way to solve is to disable the extension. This is gnome 3.30.1 on Xorg.

**Comment by ifl0w** [comment]
Hello,

are you using the newest version of the extension and does the problem occur always? Is it the first time that you are using the extension or did it work prior to some updates?

I might be able to investigate the bug if you can provide more information.

Thank you for the report!

**Comment by tnilzon** [comment]
It is on the latest "development" version of the extension and on Manjaro gnome 3.30.2
What happens it that the extension icon starts flashing when changing wallpaper. The flashing does not stop and the cpu load is high. Only way to stop it is to disable the extension.

**Comment by ifl0w** [comment]
That's weird... does checking out an older version fix the problem for you?

**Comment by tnilzon** [comment]
No, it does not.

**Comment by ifl0w** [comment]
I just pushed some fixes. They might resolve the problem for you but I sadly have no idea why this bug could be happening.

The extension does not really do anything demanding.

**Comment by ifl0w** [comment]
Is the icon flickering/flashing really fast or is it slow like "breathing"? I once stumbled over a bug in a virtual machine where the icon was flickering very fast and then a "too much recursion"  error was printed in the logs.
There was something odd happening with the tweening functions in gnome and this could probably result in a high CPU load due to the number of recursive function calls.

**Comment by tnilzon** [comment]
Hi, thanks for trying to solve this!
The answer to your question in the previous post is that the icon flashing is slow like "breathing".

**Comment by tnilzon** [comment]
Today I downloaded the latest version of the extension, and did a manual install. After running the extension for some time, and also repeatedly clicking on "New wallpaper" it seems that it is working as intended (no more "breathing" flashing of the icon)! Lets hope that the problem is solved!

**Comment by ifl0w** [comment]
The icon should "breathe"  as a status indicator if the download is taking some time. So your downloads probably are just fast enough.

Glad to hear that it is fixed for you! :+1:
