### ISSUE TITLE
[Feature Request]: "Pause" button in the extension panel icon menu.

### ISSUE THREAD

**Issue by tnilzon** [ifl0w/RandomWallpaperGnome3#49]
I have discovered the need for a "Pause" button in the extension menu (without the need to open "Settings" first). This "Pause" button should simply toggle the extension on and off (pause it on the present timer value, and continue on that timer value when un-paused). One example when I would like such "Pause" could be when working late, and a nice dark wallpaper is present and I like to stay with that for a longer while than the Auto-Fetching timer is set to. The "Pause" condition could also be indicated by a change in the panel icon, so it is easy to see the extension actual state.

**Comment by ifl0w** [comment]
This sounds like a good idea and would fit well with my ideas for the next big version update.
Basically, I planned to rewrite the complete UI and to extend the functionality quite a bit but I have no time plan for this. Maybe I'll find the time in the summer.

So it will probably take some time until this feature is added, except many people want this function and I implement it in a quick and dirty way.

I would also be happy to accept a pull request that implements this feature.
