### ISSUE TITLE
[Feature request] Change login/lockdown screen too

### ISSUE THREAD

**Issue by SonnyX** [ifl0w/RandomWallpaperGnome3#5]
I'd like to see a UI option to also change the lockdown screen :)
code I use currently:
```
_setBackground: function(path, callback){
	let background_setting = new Gio.Settings({schema: "org.gnome.desktop.background"});
	let screensaver_setting = new Gio.Settings({schema: "org.gnome.desktop.screensaver"});
	if (background_setting.is_writable("picture-uri")){
		if (background_setting.set_string("picture-uri", "file://"+path) ){
			Gio.Settings.sync();
			if (callback) {
				callback();
			}
		}
	}
	if (screensaver_setting.is_writable("picture-uri")){
		if (screensaver_setting.set_string("picture-uri", "file://"+path) ){
			Gio.Settings.sync();
			if (callback) {
				callback();
			}
		}
	}
},
```

**Comment by ifl0w** [comment]
Hello, I already thought about changing the the lockscreen image as well but I am not shure how the lockscreen image should be selected.
Am I understanding right and you just want to use the same image from the wallpaper as lockscreen all the time?

Other possibillities would be for example :
* Select another random image as lockscreen
* Use the next element of the history as lockscreen

**Comment by ifl0w** [comment]
I just implemented the feature. It is currently on the develop branch and will be available on https://extensions.gnome.org with the next release.

In your code is a little bug since the callback of the function would be executed twice. You can look at my implementation if you are interested.

Thank you for your suggestion! :+1:

**Comment by SonnyX** [comment]
Awesome, thank you!
And yeah, I didn't look too much into what the functions did, I was hasty on just seeing if it changed the lock screen, and it did. I just posted the sample code so you didn't have to look in dconf yourself :)

Another selfish request, I noticed chromecast has some cool backgrounds too.
for example refresh the next page a few times: https://clients3.google.com/cast/chromecast/home 
I noticed the following project: https://github.com/dconnolly/chromecast-backgrounds
Which makes a list of chromecast backgrounds, maybe something like this can be implemented.

**Comment by ifl0w** [comment]
The chromecast solution sounds like a good idea but it does not look like there are many different images? It should be possible to implement an adapter for the extension to use those images. Maybe I'll do that some time but I am not shure yet. :)

First I got to fix the ECMAScript and Gnome Shell version problems you encountered. 
Thank you for your brilliant help! :+1: 

Currently my favourite image source is Unsplash.com with twice my screen resolution plus a single keyword like "landscape". That really works astonishing well.

**Comment by SonnyX** [comment]
In theory the chromecast should have a huge collection of backgrounds, the following website depicts them:
http://chromecastbg.alexmeub.com/

And no hurries, I am enjoying desktoppr and the other sources just fine!

**Comment by ifl0w** [comment]
Ok well that selection seems not to be that small ^^ ... 
I'll open a feature request for that. So I do not forget to take a closer look.

**Comment by ifl0w** [comment]
@SonnyX The Chromcast image source should be easily possible with the proposed Generic JSON API source since the chromcast images can be retrieved as json with the following URL: `https://raw.githubusercontent.com/dconnolly/chromecast-backgrounds/master/backgrounds.json`

Therefore you maybe want to join the discussion of #22.
