### ISSUE TITLE
[Feature request] Save Generic JSON sources

### ISSUE THREAD

**Issue by cmcinroy** [ifl0w/RandomWallpaperGnome3#50]
Given that #22 provides the ability to define multiple JSON API sources, it would be handy to be able to define a source and name/save/add it to the source list, so that one could effectively create multiple new sources from which to fetch images.

e.g. using the great instructions in the wiki, I could create/save new sources for "Chromecast Images" and "Google Earth View" and have them in my dropdown for wallpaper source, so that I could easily switch between them.

**Comment by ifl0w** [comment]
I'll keep that in mind as I plan the next "big" release. 

I also thought about a completely new UI that allows to compose multiple sources and to store presets but this will probably not be happening too soon since I am pretty busy right now.

Thank you for the request!

**Comment by cmcinroy** [comment]
Thank you. Great extension, really enjoy it's utility.

**Comment by ifl0w** [comment]
Implemented in v3.0.0.
