### ISSUE TITLE
[Feature request] Pool of sources

### ISSUE THREAD

**Issue by BakasuraRCE** [ifl0w/RandomWallpaperGnome3#57]
With https://github.com/ifl0w/RandomWallpaperGnome3/issues/50 implementation could also be defined a pool of sources where one of them is randomly used, it would also be fantastic the possibility of enabling or disabling (and eliminating in the case of generic JSON) a source of the pool

examples of use could be to use different categories, pages, orderings, tags, searches of a JSON source

**Comment by ifl0w** [comment]
Thanks for your input! Something similar is already on my list. :+1:
