### ISSUE TITLE
The Wallhaven wallpaper source is broken since Saturday, May 25th, here is the fix.

### ISSUE THREAD

**Issue by ccoVeille** [ifl0w/RandomWallpaperGnome3#64]
So I opened PR #63 to fix it.

Feedbacks are welcomed.

**Comment by ccoVeille** [comment]
I opened an issue, just after opening an PR just in case someone else is facing the same issue I had and so avoiding him/her to chase the same dragon

**Comment by ifl0w** [comment]
The fix is merged and a new version released. 
Thank you for your help!
