### ISSUE TITLE
[Feature request] Also change unlock screen

### ISSUE THREAD

**Issue by leonardehrenfried** [ifl0w/RandomWallpaperGnome3#69]
I think it would be great if this extension would also change the _un_lock screen as in my Fedora 30 installation this is simply a grey background.

Kind of what this extension does, but integrated into RandomWallpaper: https://github.com/sunwxg/gnome-shell-extension-unlockDialogBackground

Perhaps its code can serve as an inspiration.

Thanks for a wonderful extension!

**Comment by ifl0w** [comment]
Should be supported in v3.0.0.
