### ISSUE TITLE
Support GNOME 3.34

### ISSUE THREAD

**Issue by AlexWayfer** [ifl0w/RandomWallpaperGnome3#72]
I see you've added 3.34 version to manifest in #71, but I have 3.34 on Arch Linux and this extension doesn't work.

Black screen, no wallpapers, and always "1 minute" remains:

![image](https://user-images.githubusercontent.com/6510020/65324291-7da3e500-dbb4-11e9-9bf2-b30826e6492e.png)

**Comment by ifl0w** [comment]
Yes, it is correct that some of the labels are broken. I did not look into it in detail, but it seems like a bug in the gnome-shell. Everything else works correctly for me after applying the fix from #66 again.
So, I figured that the labels are not a critical bug that I can investigate further when I have more time in the following weeks.

**Comment by mrpeabody** [comment]
It's also broken with the black screen and is not working on Gnome 3.32 Ubuntu

**Comment by AlexWayfer** [comment]
> Yes, it is correct that some of the labels are broken. I did not look into it in detail, but it seems like a bug in the gnome-shell. Everything else works correctly for me after applying the fix from #66 again.

Thank you. Yes, applying `setcap -r /usr/bin/gnome-shell` again helps, wallpapers're changing, but here is still `1 minute remaining` always.

**Comment by leonardehrenfried** [comment]
From a little bit of research it looks like the function `Gio.file_new_for_uri(uri);` doesn't support arbitrary protocols anymore, just `file:`. 

Perhaps it might work if you use an ordinary HTTP client to download the file. It seems though that the gjs HTTP client (Soup) is very, very low level.

**Comment by ifl0w** [comment]
> From a little bit of research it looks like the function `Gio.file_new_for_uri(uri);` doesn't support arbitrary protocols anymore, just `file:`.

Can you provide any sources for this information? It seems to be a bug according to [this ticket].(https://bugs.archlinux.org/task/62860)
I'd personally prefer to continue using Gio instead of Soup, if possible, due to the greater flexibility of Gio.

**Comment by leonardehrenfried** [comment]
Yes, this is also my source. I cannot prove that this is definitely the
case but I don't know of what else to try.

Would love it if you could find a better solution.

Wolfgang Rumpler <notifications@github.com> schrieb am Fr., 3. Jan. 2020,
16:05:

**Comment by AlexWayfer** [comment]
I'm not sure,  if it related, but I have also another issue with labels:

![image](https://user-images.githubusercontent.com/6510020/72053569-60686300-32d8-11ea-88fd-cad603c252f6.png)

Repeating `1.` instead of `1.`, `2.`, etc.

**Comment by ewired** [comment]
Appears to be totally broken on GNOME 3.34.4 on Solus 4.1. I'm able to go into the settings window and have it set a new background, but the dock icon does not show up and Tweaks has a warning indicator next to the extension and shows it being off. extensions.gnome.org says "ERROR" at the spot where the checkbox would normally be.
