### ISSUE TITLE
New wallpaper button and auto-fetch not working on Gnome 3.34

### ISSUE THREAD

**Issue by DrRek** [ifl0w/RandomWallpaperGnome3#73]
The button "New Wallpaper" in the bar does not work. The auto-fetch also doesn't seems to work and the timeout keeps saying "1 minute remaining". However requesting new wallpaper from the settings does work.

I'm on arch 5.3.1 using gnome 3.34.0

**Comment by ifl0w** [comment]
This is discussed in #72

Closing this duplicate.
