### ISSUE TITLE
[Feature Request] Add option to keep desktop background and change only lock screen background

### ISSUE THREAD

**Issue by elcodedocle** [ifl0w/RandomWallpaperGnome3#74]
Currently we have a setting to enable/disable changing the lock screen background. Changing the desktop background cannot be disabled. 

Would it be possible to add an option to enable/disable changing the desktop background so we can change only the lock screen background?

**Comment by ifl0w** [comment]
This feature definitely is possible. I will have a look into it when I find the time to progress development.
