### ISSUE TITLE
Supported Gnome Shell versions are not correct.

### ISSUE THREAD

**Issue by ifl0w** [ifl0w/RandomWallpaperGnome3#8]
Currently the only working Gnome Shell version is 3.24 due to usage of new ECMAScript features. With some small changes to the syntax the version 3.22 and maybe 3.20 should also work. 

Support for older versions (< 3.20 or so) will probably be dropped.

**Comment by SonnyX** [comment]
On branch: feature/inline-preview - 

`Jul 25 18:11:37 ubuntu gnome-shell[1823]: JS ERROR: Error: Type name Gjs_StatusElement is already registered
                                          GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:145
                                          wrapper@resource:///org/gnome/gjs/modules/lang.js:178
                                          Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
                                          Class@resource:///org/gnome/gjs/modules/lang.js:161
                                          @/home/sonny/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/elements.js:267
                                          @/home/sonny/.local/share/gnome-shell/extensions/randomwallpaper@iflow.space/extension.js:16
                                          initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
                                          enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:109
                                          onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:259
                                          onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:258
`

**Comment by ifl0w** [comment]
Thank you, I just pushed the fix! Though your comment would have been more suitable in #10.

The problem with `JS ERROR: Error: Type name Gjs_StatusElement is already registered`  is solved? I could not reproduce it on my machine right now.

**Comment by SonnyX** [comment]
No problem, I posted it here since I first noticed the Gjs_StatusElement error, however it was caused by the prefixText bug.

**Comment by ifl0w** [comment]
Ok I just tried the extension on in Gnome 3.14 and 3.20 and got the following error message while opening the settings on 3.14

```Gtk.BuilderError: /home/liveuser/.local/share/gnomeshell/extensions/randomwallpaper@iflow.space/settings.ui: required gtk+ version 3.20, current version is 3.14```

Therefore I'll have to drop the support for < 3.20. 
Gnome 3.20 seems to work.
