### ISSUE TITLE
Opening the settings opens the extension overview

### ISSUE THREAD

**Issue by ifl0w** [ifl0w/RandomWallpaperGnome3#85]
Opening the settings does not work correctly anymore. Currently, the extension overview where you can open the settings for all extensions is opened.

**Comment by leonardehrenfried** [comment]
I debugged into this very, very briefly and found out that this line is the culprit: https://github.com/ifl0w/RandomWallpaperGnome3/blob/develop/randomwallpaper%40iflow.space/randomWallpaperMenu.js#L92

`app` is `null`. But why?

More generally, what is a good way of finding out how to do these kind of things? I feel hopelessly lost finding information about how to write extensions.

**Comment by ifl0w** [comment]
Yeah, I found that as well and changed the app string last week (see https://github.com/ifl0w/RandomWallpaperGnome3/commit/606339ed3e3a8e511f0cfb9ff94aac8a28c17cee). The new string opens the `gnome-shell-extension-prefs` tool for me. I thought that would be better than nothing for now. Is this not working for you?
The old way of opening extension settings seems to be deprecated in favor of a newer tool (`gnome-extensions prefs randomwallpaper@iflow.space`), but I had no time to search for the correct way to execute it from the extension.

Information on extension development is pretty scarce and it takes a lot of time to search in the source code of the gnome-shell for the correct functions. Also, a lot has been changed recently and the tutorials on the internet are outdated. Especially, since Ubuntu started using Gnome by default, and the code was moved to a new GitLab Repository (https://gitlab.gnome.org/GNOME/gnome-shell/).
One of the better ways to find information right now is to dig into the code of extensions that work correctly and do what you are searching for.

The most annoying thing with extension development is that APIs are getting changed regularly without notifying developers about the upcoming changes. Most extensions, therefore, break with every major update. 
I hope that these things will change for the better since the Ubuntu Comunity and Canonical have quite some manpower to accelerate development.

**Comment by leonardehrenfried** [comment]
Ok, I figured it out: On my Fedora 32 installation, which uses Gnome 3.36, `gnome-shell-extension-prefs` was not installed. Not sure if that is the default.

Installing the package `gnome-extensions-app` made it work like you described.

Thanks for the tips about extension development. I'm a little relieved that it's not me that is stupid. The information is simply hard to find.

**Comment by ifl0w** [comment]
That's inconvenient... I thought this tool was considered a core tool of the shell and is delivered on any distribution that has a gnome-shell package.
At least for Arch Linux, it is included in the minimal package (https://www.archlinux.org/packages/extra/x86_64/gnome-shell/).

I also just found a new extension that I want to try and they fixed the same problem basically in the same way (though a bit cleaner):
https://github.com/OttoAllmendinger/gnome-shell-screenshot/blob/6dec665d398e70e8fe93dd1498cc48f04917bf28/src/indicator.js#L328

However, this should only be a temporary fix since it is definitely not optimal.

**Comment by ifl0w** [comment]
Found the necessary implementation in the arch linux update indicator extension: https://github.com/RaphaelRochet/arch-update/blob/master/extension.js#L172

Seems to work correctly.
