### ISSUE TITLE
Enhance structure to allow images from entirely different sources (e.g. local folder)

### ISSUE THREAD

**Issue by ifl0w** [ifl0w/RandomWallpaperGnome3#87]
Setting wallpapers has to be reworked a little to load files from local folders.
The architecture is not flexible enough since #77 (the update to loading images via Soup).

Either revert to the Gio.file_for_uri implementation when this bug is fixed: https://bugs.archlinux.org/task/62860
Another option is to move the `_fetchFile` function from the wallpaper controller to the BaseAdapter to allow different implementations for the fetching the files. The file should then be stored in a temporary location and moved to the correct target directory by the `wallpaperController`.

The second approach is probably the better design anyways and should not be too difficult.

**Comment by aleksfadini** [comment]
I would love to be able to choose a wallpaper from a selection of folders and subfolders on my hd. 
Someone please add this option as a source!
