### ISSUE TITLE
[Feature Request] add an option to never clear history folder

### ISSUE THREAD

**Issue by alienator** [ifl0w/RandomWallpaperGnome3#89]
Please add an option to never delete files donwloaded

**Comment by ifl0w** [comment]
Do you really want to keep all files? Or would it be better to tag selected images as favorite and never delete those?

**Comment by alienator** [comment]
Keep a favorites list of images will be the best approach

**Comment by AlexWayfer** [comment]
> Keep a favorites list of images will be the best approach

To be honest, I'm clicking on "Open Wallpaper Folder":

![image](https://user-images.githubusercontent.com/6510020/92518057-6ffdca00-f220-11ea-9347-49ef25aaa8da.png)

Then selecting "favorite" wallpapers in file manager and copy them to my personal `Wallpapers` folder.

I don't know how to automate something like this.

**Comment by ifl0w** [comment]
In this case I'll close this issue in favour of the famous #16.
