### ISSUE TITLE
Randomize subreddits before choosing random selection

### ISSUE THREAD

**Issue by noobymcnoob** [ifl0w/RandomWallpaperGnome3#91]
Hi,

Some of the subreddits I subscribe to are less popular than earthporn and so what ends up happening is I get a lot of submissions from earthporn, but very few from others.

For example, please see the frequency count of various subreddits here:

```
$ wget https://www.reddit.com/r/earthporn+spaceporn+houseporn+ruralporn.json -q -O - | jq ".data.children[].data.subreddit" | sort -nr | uniq -c
      5 "spaceporn"
      4 "ruralporn"
      1 "Houseporn"
     15 "EarthPorn"
```
As you can see, there is a high probability of getting EarthPorn results. This is not likely the result someone wants when they subscribe to multiple reddits for wallpapers, they most likely want an equal distribution.

My humble suggestion would be to randomize the subreddit selection here first and simply choose one subreddit:

https://github.com/ifl0w/RandomWallpaperGnome3/blob/beaff538f747aa1a9ba83c3c490a0068ab9d4f0c/randomwallpaper%40iflow.space/sourceAdapter.js#L356

Can become something like:

```
		let subreddits = this._settings.get('subreddits', 'string').split(',').map(s => s.trim());
		const random = Math.floor(Math.random() * subreddits.length); 
                subreddits = subreddits[random];
```

The rest of the code can remain the same.

Thank you for considering this request. I cannot live without this plugin!

**Comment by noobymcnoob** [comment]
I downloaded the code and made the following changes to make it work on my system:

```
modified   randomwallpaper@iflow.space/logger.js
@@ -1,19 +1,19 @@
 var Logger = class {
 
 	constructor(prefix, callingClass) {
 		this._prefix = prefix;
 		this._callingClass = callingClass;
 	}
 
 	_log(level, message) {
-		global.log(this._prefix + " [" + level + "] >> " + this._callingClass + " :: " + message);
+    log(this._prefix + " [" + level + "] >> " + this._callingClass + " :: " + message);
 	}
 
 	debug(message) {
 		this._log("DEBUG", message);
 	}
 
 	info(message) {
 		this._log("INFO", message);
 	}
 
modified   randomwallpaper@iflow.space/sourceAdapter.js
@@ -346,21 +346,24 @@ var RedditAdapter = class extends BaseAdapter {
 		this._settings = new SettingsModule.Settings(RWG_SETTINGS_SCHEMA_REDDIT);
 	}
 
 	_ampDecode(string) {
 		return string.replace(/\&amp;/g, '&');
 	}
 
 	requestRandomImage(callback) {
 		let session = new Soup.SessionAsync();
 
-		const subreddits = this._settings.get('subreddits', 'string').split(',').map(s => s.trim()).join('+');
+		let subreddits = this._settings.get('subreddits', 'string').split(',').map(s => s.trim());
+    const random1 = Math.floor(Math.random() * subreddits.length);
+    subreddits = subreddits[random1];
+
 		const require_sfw = this._settings.get('allow-sfw', 'boolean');
 		const url = encodeURI('https://www.reddit.com/r/' + subreddits + '.json');
 
 		let message = Soup.Message.new('GET', url);
 
 		if (message === null) {
 			this._error("Could not create request.", callback);
 			return;
 		}
 ```

**Comment by AlexWayfer** [comment]
> @noobymcnoob closed this 2 hours ago

Why? I think it can be added to the extension.

**Comment by ifl0w** [comment]
The non-uniform distribution of multiple subreddits is a tricky issue.
Unfortunately, the presented implementation does not provide the desired behavior, and implementing it correctly is probably not worth it.

The request returns only 25 of the – I think – most recent posts. This limit can be increased to 100 by adding a query parameter `limit=100`.For two subreddits A and B we want to select from every subreddit with a chance of 50%.
Say A has 100 times more posts than B. Then a single post in B will be in the response until A had 100 posts.
During this time we would select the same image from subreddit B for every second wallpaper change. This is definitely not the desired behavior.

A better implementation would would access the stored history in order to get a better distribution but this would require more effort.

**Comment by ifl0w** [comment]
This can now be done with multiple Reddit sources in v3.0.0.
