### ISSUE TITLE
Not working on 3.38.0

### ISSUE THREAD

**Issue by evfool** [ifl0w/RandomWallpaperGnome3#92]
As gnome-shell has transitioned from using tweener to clutter animations and tweener was dropped, random wallpaper fails to load on 3.38.0 with the message `No JS module 'tweener' found in search path`

**Comment by evfool** [comment]
Relevant gnome-shell commit is:
https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/b3b91f1699e92c3dbaaa5965851394a7306f1398

**Comment by crashbit666** [comment]
Yeah! Same problem with Gnome 3.38 on Arch Linux

**Comment by ifl0w** [comment]
Should be fixed and will be released as soon as I have time for proper testing. Thanks for reporting and helping!
