### ISSUE TITLE
Unsplash 401, change parameter order

### ISSUE THREAD

**Issue by ChrisG661** [ifl0w/RandomWallpaperGnome3#94]
Hello,
I have just downloaded this extension for retrieving wallpaper from Unsplash. At first, it didn't work and is stuck at loading. From what I have tested, `client_id` parameter should be the first parameter in the first request. Am i the only one experiencing this?

**Comment by ifl0w** [comment]
Hello, I am not entirely sure what you are referring to.
The Unsplash source still works the same for me as it used to and the order of query parameters in a HTTP request should not make any difference.
You might want to elaborate on your issue if I didn't understand it correctly.

**Comment by ChrisG661** [comment]
When i do the same as the code url:
`curl -XGET https://api.unsplash.com/photos/random?w=1920&h=1080&client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d`
It returns this `{"errors":["OAuth error: The access token is invalid"]}`
However if i put the `client_id` parameter first:
`curl -XGET https://api.unsplash.com/photos/random?client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d&w=1920&h=1080`
It works and returns the image ID.
I am using PopOS 20.04.

**Comment by AlexWayfer** [comment]
> When i do the same as the code url:
> `curl -XGET https://api.unsplash.com/photos/random?w=1920&h=1080&client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d`
> It returns this `{"errors":["OAuth error: The access token is invalid"]}`
> However if i put the `client_id` parameter first:
> `curl -XGET https://api.unsplash.com/photos/random?client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d&w=1920&h=1080`
> It works and returns the image ID.
> I am using PopOS 20.04.

Try this please:

```
curl -XGET "https://api.unsplash.com/photos/random?w=1920&h=1080&client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d"
```

Some shells can have meta chars, like `?`, `&`, etc.

For example, I've escaped highlighted `&` and forgot about `?`, so I had such errors:

```
> curl -XGET https://api.unsplash.com/photos/random?w=1920\&h=1080\&client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d
fish: No matches for wildcard “https://api.unsplash.com/photos/random?w=1920\&h=1080\&client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d”. See `help expand`.
curl -XGET https://api.unsplash.com/photos/random?w=1920\&h=1080\&client_id=64daf439e9b579dd566620c0b07022706522d87b255d06dd01d5470b7f193b8d
           ^
```

The best way is to use quotes for strings.

**Comment by ifl0w** [comment]
Alex has pointed to a valid issue of your observation.

If the extension does not work for you, then it is very likely due to some other reason.
