### ISSUE TITLE
Change folder

### ISSUE THREAD

**Issue by ChauhanT** [ifl0w/RandomWallpaperGnome3#95]
Hi, 

I was wondering if there is a way to change the folder where wallpapers are stored. I don't know if this is the place to ask.

Cheers

**Comment by ifl0w** [comment]
Hello!

Here is probably the best place for asking these things.

Unfortunately, the wallpaper location is hardcoded in this line [here](https://github.com/ifl0w/RandomWallpaperGnome3/blob/84a828b3c2094a6700d67a1652ae7d54d803b388/randomwallpaper%40iflow.space/wallpaperController.js#L23).
There is already the issue #86 for making it user changable but I did not have the time to implement the UI for it.
So for now, you have to change it in the code yourself if you want to use some different storage location.

Have a nice day!

Closing this issue in favor of #86.

**Comment by ChauhanT** [comment]
@ifl0w Thank you for such a rapid response, and even more so for sharing the plugin with the community. Cheers!
